/**
 * 改善案生成 サーバー側一元化 Callable Function
 *
 * クライアント側の generateAndAddImprovements.js (400行) をサーバー側に移動。
 * 1. 包括的データ取得（GA4/GSC/Firestore直接アクセス）
 * 2. AI改善案生成（generateAISummary内部ロジック呼び出し）
 * 3. Jaccard類似度による重複排除
 * 4. Firestore保存 + 非ビジュアル改善のmockupSkipped設定
 */
import { HttpsError } from 'firebase-functions/v2/https';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { logger } from 'firebase-functions/v2';
import { canAccessSite } from '../utils/permissionHelper.js';
import { fetchComprehensiveDataForImprovement } from '../utils/serverComprehensiveDataFetcher.js';
import { enforceRateLimit, DEFAULT_RATE_LIMITS } from '../utils/rateLimiter.js';
import { requireDocId, requireEnum, optionalMessage, optionalString, requireBoolean, MAX_USER_NOTE_LEN } from '../utils/validators.js';

const JACCARD_THRESHOLD = 0.5;

// ==================== 重複判定ユーティリティ ====================

function normalizeTitle(s) {
  return (s || '').trim().replace(/\s+/g, ' ');
}

function bigramSet(str) {
  const n = normalizeTitle(str);
  const set = new Set();
  for (let i = 0; i < n.length - 1; i++) {
    set.add(n.slice(i, i + 2));
  }
  return set;
}

function jaccardSimilarity(a, b) {
  const sa = bigramSet(a);
  const sb = bigramSet(b);
  if (sa.size === 0 && sb.size === 0) return 1;
  let intersection = 0;
  for (const x of sa) {
    if (sb.has(x)) intersection++;
  }
  const union = sa.size + sb.size - intersection;
  return union === 0 ? 0 : intersection / union;
}

function extractPathFromTitleOrDescription(title, description) {
  const text = [title, description].filter(Boolean).join(' ');
  if (!text) return null;
  const parenMatch = text.match(/[（(](\/[^）)]*\/?)[）)]/);
  if (parenMatch?.[1]) return parenMatch[1].trim() || '/';
  // 前置文字として空白/文頭/カッコ/句点を要求（"UI/UX" の UX を誤抽出しないため）
  const pathMatch = text.match(/(?:^|[\s「『（(【、。，])(\/[a-zA-Z0-9/_.-]+)/);
  if (pathMatch?.[1]) {
    const p = pathMatch[1];
    // /UX /UI /AI /CV 等の短い英大文字略語は誤抽出の可能性が高いので除外
    if (/^\/[A-Z]{2,4}$/.test(p)) return null;
    return p;
  }
  return null;
}

// 非ビジュアル改善キーワード
const NON_VISUAL_KEYWORDS = [
  '読込速度', '読み込み速度', '表示速度', 'ページ速度', 'パフォーマンス',
  'Core Web Vitals', 'LCP', 'FID', 'CLS', 'TTFB', 'INP',
  'alt属性', 'メタディスクリプション', 'meta description',
  'robots.txt', 'sitemap', 'canonical', 'hreflang',
  '構造化データ', 'schema.org', 'JSON-LD',
  'SSL', 'HTTPS', 'セキュリティ',
  'キャッシュ', 'CDN', '圧縮', 'minify', 'gzip',
  'リダイレクト', '301', '302', '404',
  'アクセシビリティ', 'WCAG',
];

function isNonVisual(title, description) {
  // URL を除去してから判定（URL 内の "https"/"404" 等が誤マッチするため）
  const raw = `${title || ''} ${description || ''}`;
  const text = raw.replace(/https?:\/\/[^\s）)」』】＞>"']+/gi, '').toLowerCase();
  return NON_VISUAL_KEYWORDS.some(kw => {
    const lower = kw.toLowerCase();
    // ASCII のみ（INP, 404, HTTPS 等）は単語境界マッチで誤判定回避
    if (/^[\x20-\x7E]+$/.test(kw)) {
      const escaped = lower.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(`(?:^|[^a-z0-9])${escaped}(?![a-z0-9])`, 'i');
      return re.test(text);
    }
    return text.includes(lower);
  });
}

// カテゴリ/優先度の正規化
const categoryMap = {
  content: 'content', コンテンツ: 'content', コンテント: 'content',
  design: 'design', デザイン: 'design',
  acquisition: 'acquisition', 集客: 'acquisition',
  feature: 'feature', 機能: 'feature',
  technical: 'other', 技術: 'other',
  other: 'other', その他: 'other',
};
const priorityMap = {
  high: 'high', 高: 'high',
  medium: 'medium', 中: 'medium',
  low: 'low', 低: 'low',
};

function normalizeCategory(v) {
  if (!v || typeof v !== 'string') return 'other';
  const key = v.trim().toLowerCase();
  return categoryMap[key] ?? 'other';
}

function normalizePriority(v) {
  if (!v || typeof v !== 'string') return 'medium';
  const key = v.trim().toLowerCase();
  return priorityMap[key] || 'medium';
}

// ==================== メインハンドラ ====================

export async function generateImprovementsCallable(req) {
  if (!req.auth) {
    throw new HttpsError('unauthenticated', 'ユーザー認証が必要です');
  }

  const userId = req.auth.uid;

  // Phase 4-A-2: レート制限（AI コール課金枯渇防止）
  await enforceRateLimit({ uid: userId, ...DEFAULT_RATE_LIMITS.generateImprovements });

  // 入力検証 (Phase 4-B-7)
  const rawData = req.data || {};
  const siteId = requireDocId(rawData.siteId, 'siteId');
  const improvementFocus = requireEnum(
    rawData.improvementFocus || 'balance',
    'improvementFocus',
    ['balance', 'acquisition', 'conversion', 'branding', 'usability', 'performance']
  );
  const userNote = optionalMessage(rawData.userNote, 'userNote', MAX_USER_NOTE_LEN);
  // forceRegenerate は型チェックのみ実施（後続処理では generateAISummary 内部で常に true を渡すため未使用）
  if (rawData.forceRegenerate !== undefined) requireBoolean(rawData.forceRegenerate, 'forceRegenerate');
  const autoGenerated = rawData.autoGenerated === undefined ? false : requireBoolean(rawData.autoGenerated, 'autoGenerated');
  const triggeredBy = optionalString(rawData.triggeredBy || 'manual', 'triggeredBy', { maxLen: 64 });
  const reqStartDate = optionalString(rawData.startDate, 'startDate', { maxLen: 32 });
  const reqEndDate = optionalString(rawData.endDate, 'endDate', { maxLen: 32 });

  if (!siteId) {
    throw new HttpsError('invalid-argument', 'siteIdが必要です');
  }

  // 権限チェック
  // viewer も AI 改善案生成は許可（オーナーのプラン枠を消費）。
  // 手動編集は Firestore Rules / 個別 callable 側でブロックする。
  const hasAccess = await canAccessSite(userId, siteId);
  if (!hasAccess) {
    throw new HttpsError('permission-denied', 'このサイトの改善案を生成する権限がありません');
  }

  const db = getFirestore();
  const startTime = Date.now();

  logger.info('[generateImprovements] 開始', { siteId, improvementFocus, userId });

  try {
    // Step 1: プラン制限チェック（自動生成時はautoImprovementGenerator側でチェック済みのためスキップ）
    if (!autoGenerated) {
      const { checkCanGenerate } = await import('../utils/planManager.js');
      const canGen = await checkCanGenerate(userId, 'improvement');
      if (!canGen) {
        throw new HttpsError('resource-exhausted', '月間のAI改善生成回数の上限に達しました');
      }
    }

    // Step 2: サイトデータ取得
    const siteDoc = await db.collection('sites').doc(siteId).get();
    if (!siteDoc.exists) throw new HttpsError('not-found', 'サイトが見つかりません');
    const siteData = siteDoc.data();
    const siteUrl = (siteData.siteUrl || '').trim().replace(/\/+$/, '');

    // Step 3: 既存改善案を取得（重複チェック用）
    const existingSnap = await db.collection('sites').doc(siteId).collection('improvements').get();
    const existingForPrompt = existingSnap.docs
      .filter(d => {
        const status = d.data().status;
        return status === 'draft' || status === 'in_progress';
      })
      .map(d => ({ title: d.data().title || '', description: d.data().description || '' }));

    const existingTitles = existingSnap.docs
      .filter(d => d.data().status !== 'completed')
      .map(d => normalizeTitle(d.data().title || ''));
    const existingDedupKeys = new Set(
      existingSnap.docs
        .filter(d => d.data().status !== 'completed')
        .map(d => (d.data().dedupKey || '').trim().toLowerCase())
        .filter(Boolean)
    );

    // Step 4: 包括的データ取得
    // dateRange が指定されていればその期間、なければデフォルト（直近30日）
    logger.info('[generateImprovements] データ取得開始', { reqStartDate, reqEndDate });
    const fetchOptions = (reqStartDate && reqEndDate) ? { startDate: reqStartDate, endDate: reqEndDate } : {};
    const comprehensiveData = await fetchComprehensiveDataForImprovement(siteId, fetchOptions);
    logger.info('[generateImprovements] データ取得完了');

    // Step 4.5: improvementFocus='auto' の場合、データ傾向から自動判定
    let resolvedFocus = improvementFocus;
    let autoFocusNote = '';
    if (improvementFocus === 'auto') {
      resolvedFocus = 'balance';
      autoFocusNote = '※ サイトの最新データに基づき、AIが最もインパクトの大きい改善領域を自動判定してください。特定のフォーカスに偏らず、データから読み取れる課題を優先してください。';
    }

    // Step 5: AI改善案生成（generateAISummaryの内部ロジックを直接呼び出し）
    const today = new Date();
    const thirtyDaysAgo = new Date(today);
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    const startDate = today.toISOString().split('T')[0];
    const endDate = thirtyDaysAgo.toISOString().split('T')[0];

    const { generateAISummaryCallable } = await import('./generateAISummary.js');
    const aiResult = await generateAISummaryCallable({
      auth: req.auth,
      data: {
        siteId,
        pageType: 'comprehensive_improvement',
        startDate: endDate,
        endDate: startDate,
        metrics: comprehensiveData,
        forceRegenerate: true,
        improvementFocus: resolvedFocus,
        userNote: autoFocusNote ? `${autoFocusNote}\n${userNote}`.trim() : userNote,
        existingImprovements: existingForPrompt,
      },
    });

    const recommendations = aiResult.recommendations || [];
    logger.info(`[generateImprovements] AI生成完了: ${recommendations.length}件`);

    if (recommendations.length === 0) {
      return { success: true, count: 0, improvementIds: [], message: '推奨施策が見つかりませんでした' };
    }

    // Step 6: Jaccard類似度による重複排除
    const filtered = [];
    const seenDedupKeys = new Set();
    for (const rec of recommendations) {
      const title = normalizeTitle(rec.title);
      const dedupKey = (rec.dedupKey || '').trim().toLowerCase();

      if (dedupKey && existingDedupKeys.has(dedupKey)) continue;
      if (dedupKey && seenDedupKeys.has(dedupKey)) continue;

      let tooSimilar = false;
      for (const existing of existingTitles) {
        if (jaccardSimilarity(title, existing) >= JACCARD_THRESHOLD) {
          tooSimilar = true;
          break;
        }
      }
      if (tooSimilar) continue;

      for (const other of filtered) {
        if (jaccardSimilarity(title, normalizeTitle(other.title)) >= JACCARD_THRESHOLD) {
          tooSimilar = true;
          break;
        }
      }
      if (tooSimilar) continue;

      if (dedupKey) seenDedupKeys.add(dedupKey);
      filtered.push(rec);
    }

    if (filtered.length === 0) {
      return { success: true, count: 0, improvementIds: [], message: '新規の改善案はありません（全て既存と重複）' };
    }

    logger.info(`[generateImprovements] 重複除外後: ${filtered.length}件`);

    // Step 7: Firestore保存
    const buildTargetPageUrl = (pathOrUrl) => {
      if (!pathOrUrl || pathOrUrl === '/') return '';
      if (pathOrUrl.startsWith('http://') || pathOrUrl.startsWith('https://')) return pathOrUrl;
      if (!siteUrl) return '';
      const path = pathOrUrl.startsWith('/') ? pathOrUrl : `/${pathOrUrl}`;
      return `${siteUrl}${path}`;
    };

    // ユーザーメール取得
    const userDoc = await db.collection('users').doc(userId).get();
    const userEmail = userDoc.exists ? (userDoc.data()?.email || 'unknown') : 'unknown';

    const improvementIds = [];

    for (let i = 0; i < filtered.length; i += 250) {
      const chunk = filtered.slice(i, i + 250);
      const batch = db.batch();

      for (const suggestion of chunk) {
        let targetPagePath = (suggestion.targetPagePath || suggestion.targetPageUrl || '').trim();
        // 2026-05-08: AI が targetPagePath: '/' (ルート) を返してくるケースがあり、
        // description には具体パス (「/works/」等) が書かれているのに extraction が
        // skip されて targetPageUrl が空になる問題があった。'/' も未設定扱いにして
        // description からの抽出を試みる。
        if (!targetPagePath || targetPagePath === '/') {
          const extracted = extractPathFromTitleOrDescription(suggestion.title, suggestion.description);
          if (extracted && extracted !== '/') targetPagePath = extracted;
        }
        const targetPageUrl = buildTargetPageUrl(targetPagePath);
        const hours = suggestion.estimatedLaborHours;
        const estimatedLaborHours = (hours != null && !Number.isNaN(Number(hours)) && Number(hours) > 0)
          ? Number(hours) : null;

        const nonVisual = isNonVisual(suggestion.title, suggestion.description);

        const ref = db.collection('sites').doc(siteId).collection('improvements').doc();
        batch.set(ref, {
          title: suggestion.title,
          description: suggestion.description,
          status: 'draft',
          expectedImpact: suggestion.expectedImpact || '',
          targetPageUrl: targetPageUrl || '',
          targetArea: suggestion.targetArea || '',
          category: normalizeCategory(suggestion.category),
          priority: normalizePriority(suggestion.priority),
          estimatedLaborHours,
          dedupKey: suggestion.dedupKey || null,
          order: Date.now(),
          createdAt: FieldValue.serverTimestamp(),
          updatedAt: FieldValue.serverTimestamp(),
          createdBy: userEmail,
          source: 'ai_generated',
          autoGenerated: autoGenerated || false,
          triggeredBy: triggeredBy || 'manual',
          ...(autoGenerated ? { autoGeneratedAt: FieldValue.serverTimestamp() } : {}),
          // 非ビジュアル改善はモックアップスキップ
          ...(nonVisual ? { mockupSkipped: true, mockupSkipReason: 'non_visual' } : {}),
          // タクソノミー V2 施策タグ基盤（雛形のみ、AI 自動付与は別フェーズで実装）
          tags: [],
          tagCategory: '',
        });
        improvementIds.push(ref.id);
      }

      await batch.commit();
    }

    // Before スクショの撮影はフロント側（Improve.jsx）が改善一覧を検知した瞬間、
    // 並列度4で captureBeforeScreenshot Callable を叩いて裏で撮影する方式。
    // サーバ側では撮影しない（fire-and-forget はコンテナ停止で切れるリスクがあるため）。

    const duration = Date.now() - startTime;
    logger.info(`[generateImprovements] 完了: ${improvementIds.length}件保存 (${duration}ms)`);

    return {
      success: true,
      count: improvementIds.length,
      improvementIds,
      message: `${improvementIds.length}件の改善案を生成しました`,
    };
  } catch (error) {
    logger.error('[generateImprovements] エラー:', error);
    if (error instanceof HttpsError) throw error;
    throw new HttpsError('internal', `改善案生成に失敗しました: ${error.message}`);
  }
}
