/**
 * AI改善提案の自動生成ユーティリティ
 *
 * 月次スクレイピング完了後に自動で改善提案を生成する。
 * - autoImprovementEnabled チェック
 * - Freeプラン除外
 * - 30日クールダウン
 * - プラン月間回数消費
 * - 既存 generateImprovementsCallable を内部呼び出し
 * - 通知（アプリ内アラート + メール）
 */
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { logger } from 'firebase-functions/v2';

const MAX_RETRIES = 3;
const COOLDOWN_MS = 30 * 24 * 60 * 60 * 1000; // 30日

/**
 * サイトの自動改善提案を生成
 * @param {string} siteId
 * @returns {Promise<{success: boolean, count?: number, skipped?: boolean, reason?: string}>}
 */
export async function generateAutoImprovements(siteId) {
  const db = getFirestore();

  logger.info('[AutoImprovement] 自動生成チェック開始', { siteId });

  // Step 1: サイト設定チェック
  const siteDoc = await db.collection('sites').doc(siteId).get();
  if (!siteDoc.exists) {
    logger.warn('[AutoImprovement] サイトが見つかりません', { siteId });
    return { success: false, skipped: true, reason: 'サイトが見つかりません' };
  }

  const siteData = siteDoc.data();

  if (!siteData.autoImprovementEnabled) {
    logger.info('[AutoImprovement] 自動生成が無効', { siteId });
    return { success: true, skipped: true, reason: '自動生成が無効' };
  }

  // Step 2: 30日クールダウンチェック
  const lastAutoAt = siteData.lastAutoImprovementAt;
  if (lastAutoAt) {
    const lastTime = lastAutoAt.toDate ? lastAutoAt.toDate().getTime() : new Date(lastAutoAt).getTime();
    if (Date.now() - lastTime < COOLDOWN_MS) {
      logger.info('[AutoImprovement] 30日以内に自動生成済み、スキップ', { siteId });
      return { success: true, skipped: true, reason: '30日以内に自動生成済み' };
    }
  }

  // Step 3: サイトオーナーのプランチェック
  const ownerId = siteData.userId;
  if (!ownerId) {
    logger.warn('[AutoImprovement] サイトオーナーが不明', { siteId });
    return { success: false, skipped: true, reason: 'オーナー不明' };
  }

  const { checkCanGenerate, incrementGenerationCount } = await import('./planManager.js');

  // Freeプランチェック
  const userDoc = await db.collection('users').doc(ownerId).get();
  const userData = userDoc.exists ? userDoc.data() : null;
  const plan = userData?.plan || 'free';

  if (plan === 'free') {
    logger.info('[AutoImprovement] Freeプランのため自動生成不可', { siteId, ownerId });
    return { success: true, skipped: true, reason: 'Freeプランのため自動生成不可' };
  }

  // 月間回数チェック
  const canGenerate = await checkCanGenerate(ownerId, 'improvement');
  if (!canGenerate) {
    logger.info('[AutoImprovement] 月間生成回数上限に達しています', { siteId, ownerId });
    return { success: true, skipped: true, reason: '月間生成回数上限' };
  }

  // Step 4: 改善提案を生成（リトライ付き）
  let lastError = null;
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      logger.info('[AutoImprovement] 生成実行', { siteId, attempt });

      const { generateImprovementsCallable } = await import('../callable/generateImprovements.js');
      const result = await generateImprovementsCallable({
        auth: { uid: ownerId },
        data: {
          siteId,
          improvementFocus: 'auto',
          forceRegenerate: true,
          autoGenerated: true,
          triggeredBy: 'monthly_scrape',
        },
      });

      // Step 5: 成功 → メタデータ更新
      await db.collection('sites').doc(siteId).update({
        lastAutoImprovementAt: FieldValue.serverTimestamp(),
      });

      // Step 6: プラン回数消費
      await incrementGenerationCount(ownerId, 'improvement');

      // Step 7: 通知
      const count = result.count || 0;
      if (count > 0) {
        await sendAutoImprovementNotification(db, siteId, siteData, ownerId, count);
      }

      logger.info('[AutoImprovement] 自動生成完了', { siteId, count });
      return { success: true, count };

    } catch (error) {
      lastError = error;
      logger.warn('[AutoImprovement] 生成エラー（リトライ）', { siteId, attempt, error: error.message });

      if (attempt < MAX_RETRIES) {
        await new Promise(resolve => setTimeout(resolve, attempt * attempt * 1000));
      }
    }
  }

  // Step 8: 全リトライ失敗 → エラーアラート
  logger.error('[AutoImprovement] 全リトライ失敗', { siteId, error: lastError?.message });

  try {
    await db.collection('sites').doc(siteId).collection('alerts').add({
      type: 'auto_improvement_error',
      message: `AI改善提案の自動生成に失敗しました。手動で再生成してください。`,
      createdAt: new Date(),
    });
  } catch (alertError) {
    logger.warn('[AutoImprovement] エラーアラート保存失敗', { siteId, error: alertError.message });
  }

  return { success: false, reason: lastError?.message };
}

/**
 * 自動生成完了通知（アプリ内アラート + メール）
 */
async function sendAutoImprovementNotification(db, siteId, siteData, ownerId, count) {
  const siteName = siteData.siteName || siteData.siteUrl || 'サイト';

  // アプリ内アラート
  try {
    await db.collection('sites').doc(siteId).collection('alerts').add({
      type: 'auto_improvement_completed',
      message: `「${siteName}」に${count}件の新しいAI改善提案が自動生成されました。`,
      link: '/improve',
      createdAt: new Date(),
    });
  } catch (error) {
    logger.warn('[AutoImprovement] アラート保存エラー', { siteId, error: error.message });
  }

  // メール通知
  try {
    const userDoc = await db.collection('users').doc(ownerId).get();
    const userData = userDoc.exists ? userDoc.data() : null;
    const notificationSettings = userData?.notificationSettings || {};

    if (notificationSettings.alertEmail !== false) {
      const email = userData?.email;
      if (email) {
        const { sendEmailDirect } = await import('./emailSender.js');
        await sendEmailDirect({
          to: email,
          subject: `【GrowReporter】${siteName}のAI改善提案が更新されました`,
          html: buildAutoImprovementEmailHtml(siteName, count),
        });
        logger.info('[AutoImprovement] メール通知送信完了', { siteId, email });
      }
    }
  } catch (error) {
    logger.warn('[AutoImprovement] メール送信エラー', { siteId, error: error.message });
  }
}

function buildAutoImprovementEmailHtml(siteName, count) {
  return `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <h2 style="color: #1B2559; font-size: 18px;">AI改善提案が更新されました</h2>
      <p style="color: #637381; font-size: 14px; line-height: 1.6;">
        「${siteName}」に<strong>${count}件</strong>の新しい改善提案が自動生成されました。
        最新のサイトデータに基づいた提案です。
      </p>
      <p style="margin-top: 24px;">
        <a href="https://growgroupreporter.web.app/improve"
           style="display: inline-block; background: #3758F9; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-size: 14px; font-weight: 500;">
          改善提案を確認する
        </a>
      </p>
      <p style="color: #9CA3AF; font-size: 12px; margin-top: 32px;">
        この通知はGrowReporterの自動改善提案機能によるものです。<br>
        通知設定はアカウント設定から変更できます。
      </p>
    </div>
  `;
}
